### ISSUE TITLE
AES 256 CBC 加密出来的内容不一样

### ISSUE THREAD

**Issue by hel2o** [wumansgy/goEncrypt#12]
通过这个网站在线加密出来的内容如下
![图片](https://user-images.githubusercontent.com/14226648/144771122-b5d42926-d441-4314-bb32-658de50901c9.png)
![图片](https://user-images.githubusercontent.com/14226648/144771543-9493e72b-4b79-462c-b3c5-ab032fd9bfea.png)
AES的CBC模式加密后的密文为: ca50cdf49d7be7153286c34f6a4a678a10c41dd2c635989832b034df559cb74b76bc5e9ab6055a19efcd8afe58b27f528c078c4006c27d2f1cf7fab4be3bae641b2ede777ec15cd62bc8de96cf8a16293358f91f3dcf27bdae91dfd307fc0cc0a2c71fc198bf12be64166ef9c2f3309ef839ca6f0571882b7d77260d295beab2c9ce39382e1b2b3d3ed8f017093c6369c0ded230fe2a8c26d348ddb0f7162e05

两个加密出来不一样，能请问这是什么原因？

**Comment by wumansgy** [comment]
pkcs5 pkcs7  后面加上pkcs7
