### ISSUE TITLE
sha256和sha512问题

### ISSUE THREAD

**Issue by susengo** [wumansgy/goEncrypt#2]
你好，以下这些函数是否未实现啊？
goEncrypt.GetFileStringHash256
goEncrypt.GetStringHash256
goEncrypt.GetFileStringHash512
goEncrypt.GetStringHash512
goEncrypt.GetFileHash256
goEncrypt.GetFileHash512
goEncrypt.GetHash256
goEncrypt.GetHash512

**Comment by wumansgy** [comment]
已经更新文档，看一下使用文档
