### ISSUE TITLE
go get 无法切换到v2.0.0 版本

### ISSUE THREAD

**Issue by zyn110123** [wumansgy/goEncrypt#21]
go: github.com/wumansgy/goEncrypt@v2.0.0: reading https://goproxy.io/github.com/wumansgy/go%21encrypt/@v/v2.0.0.info: 404 Not Found

**Comment by wumansgy** [comment]
v2需要改路径 我删了重新打了版本  v1.1.0 可以了

**Comment by zyn110123** [comment]
感恩！~
