### ISSUE TITLE
关于椭圆曲线加密算法的计算问题

### ISSUE THREAD

**Issue by Neronjust2017** [wumansgy/goEncrypt#23]
大佬，可能是一个非常简单且愚蠢的问题：既然椭圆曲线上代数计算满足结合律，那么是否可以用快速幂算法（时间复杂度是对数级别的）来计算某个大数k对应的值？反过来，在知道kP和P的前提下，要反推k，无法使用快速幂算法，没有比挨个尝试更快的方法了（几乎是不可能的），不知道我理解的对吗？

**Comment by wumansgy** [comment]
在椭圆曲线上有类似快速幂的算法 倍增,无法使用快速幂算法是对的，但是没有比一个个计算更快的方法这个不那么正确,有很多技巧可以帮助加快一个个尝试的速度,你分点去预计算，可以减少重复计算或者说可以并行处理
