### ISSUE TITLE
runtime err: runtime error: invalid memory address or nil pointer dereference Check that the key is correct

### ISSUE THREAD

**Issue by stuhk** [wumansgy/goEncrypt#3]
runtime err: runtime error: invalid memory address or nil pointer dereference Check that the key is correct

cryptText,_:=goEncrypt.RsaEncrypt([]byte("aaa"),[]byte{ 48, 129, 159, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1, 5, 0, 3, 129, 141, 0, 48, 129, 137, 2, 129, 129, 0, 193, 227, 147, 77, 22, 20, 70, 91, 51, 5, 62, 127, 72, 238, 78, 200, 123, 20, 185, 94, 248, 137, 71, 113, 61, 37, 238, 203, 255, 126, 116, 199, 151, 125, 2, 220, 29, 148, 81, 247, 157, 213, 209, 193, 12, 41, 172, 182, 169, 180, 214, 251, 125, 10, 2, 121, 182, 113, 158, 23, 114, 86, 95, 9, 175, 98, 119, 21, 145, 146, 33, 174, 249, 24, 153, 202, 224, 140, 13, 104, 109, 116, 139, 32, 163, 96, 59, 226, 49, 140, 166, 188, 43, 89, 112, 101, 146, 169, 33, 157, 11, 240, 92, 159, 101, 2, 58, 33, 210, 51, 8, 7, 37, 42, 224, 6, 109, 89, 206, 239, 165, 242, 116, 142, 168, 11, 171, 129, 2, 3, 1, 0, 1 })
	fmt.Println(cryptText)

**Comment by wumansgy** [comment]
rsa加密需要秘钥 你的秘钥传错了 看使用文档
