### ISSUE TITLE
请问下rsa有没有私钥加密公钥解密的方法呢？

### ISSUE THREAD

**Issue by bingoIsCoder** [wumansgy/goEncrypt#7]

**Comment by JerryZhou343** [comment]
这样的场景是签名；
签名： goEncrypt.RsaSign  （私钥加密）
验签： goEncrypt.RsaVerifySign (公钥解密）

**Comment by wumansgy** [comment]
私钥签名，公钥验签 （试着想一下，私钥加密的话，公钥是公开的如果可以解密的话那谁都可以解密那就不存在加密一说，所以没有私钥加密公钥解密这一说，只有私钥签名，公钥验证签名）
