### ISSUE TITLE
aes的cbc模式下的iv向量传入类型应该改为[]byte类型吧

### ISSUE THREAD

**Issue by daofeng2015** [wumansgy/goEncrypt#9]
到函数里面最后也是[]byte来操作的,传byte这个类型不好搞啊,还有能不能也支持多种填充模式啊,默认也是写死的PKCS5Padding

**Comment by wumansgy** [comment]
OK 我看看怎么改

**Comment by wumansgy** [comment]
> 到函数里面最后也是[]byte来操作的,传byte这个类型不好搞啊,还有能不能也支持多种填充模式啊,默认也是写死的PKCS5Padding
OK
